##===- flang/lib/Parse/Makefile ----------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the Parser library for the Fortran front-end.
#
##===----------------------------------------------------------------------===##

FLANG_LEVEL := ../..
LIBRARYNAME := flangParse

include $(FLANG_LEVEL)/Makefile
