##===- lib/Makefile ----------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

FLANG_LEVEL := ..

PARALLEL_DIRS = Basic Parse AST Frontend

include $(FLANG_LEVEL)/Makefile
