##===- tools/Makefile --------------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

FLANG_LEVEL := ..
DIRS := driver

include $(FLANG_LEVEL)/../../Makefile.config

include $(FLANG_LEVEL)/Makefile
